/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class interfaces_InterfaceJavaC */

#ifndef _Included_interfaces_InterfaceJavaC
#define _Included_interfaces_InterfaceJavaC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     interfaces_InterfaceJavaC
 * Method:    debutPartie
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_interfaces_InterfaceJavaC_debutPartie
  (JNIEnv *, jclass, jint);

/*
 * Class:     interfaces_InterfaceJavaC
 * Method:    jouer
 * Signature: (IIC)Z
 */
JNIEXPORT jboolean JNICALL Java_interfaces_InterfaceJavaC_jouer
  (JNIEnv *, jclass, jint, jint, jchar);

/*
 * Class:     interfaces_InterfaceJavaC
 * Method:    getCase
 * Signature: (II)C
 */
JNIEXPORT jchar JNICALL Java_interfaces_InterfaceJavaC_getCase
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     interfaces_InterfaceJavaC
 * Method:    retourArriere
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_interfaces_InterfaceJavaC_retourArriere
  (JNIEnv *, jclass);

/*
 * Class:     interfaces_InterfaceJavaC
 * Method:    supprimerPlateau
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_interfaces_InterfaceJavaC_supprimerPlateau
  (JNIEnv *, jclass);

/*
 * Class:     interfaces_InterfaceJavaC
 * Method:    sauvegarder
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_interfaces_InterfaceJavaC_sauvegarder
  (JNIEnv *, jclass, jstring);

/*
 * Class:     interfaces_InterfaceJavaC
 * Method:    charger
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_interfaces_InterfaceJavaC_charger
  (JNIEnv *, jclass, jstring);

/*
 * Class:     interfaces_InterfaceJavaC
 * Method:    estTerminePartie
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_interfaces_InterfaceJavaC_estTerminePartie
  (JNIEnv *, jclass);

/*
 * Class:     interfaces_InterfaceJavaC
 * Method:    getTaille
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_interfaces_InterfaceJavaC_getTaille
  (JNIEnv *, jclass);

/*
 * Class:     interfaces_InterfaceJavaC
 * Method:    getNbrCoup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_interfaces_InterfaceJavaC_getNbrCoup
  (JNIEnv *, jclass);

/*
 * Class:     interfaces_InterfaceJavaC
 * Method:    coupIA
 * Signature: (CI)V
 */
JNIEXPORT void JNICALL Java_interfaces_InterfaceJavaC_coupIA
  (JNIEnv *, jclass, jchar, jint);

#ifdef __cplusplus
}
#endif
#endif
